### PR TITLE
Scala 2.13.0

### PR DESCRIPTION
**Pull request by jhnsmth**

### CODE REVIEW

**Comment by travisbrown** [comment]
Thanks!

**Comment by larsrh** [comment]
@travisbrown Are you running the release?

**Comment by travisbrown** [comment]
@larsrh We need to make a decision on versioning first—see my question [here](https://gitter.im/typelevel/cats-dev?at=5cff8ce9b76eac527adda9a7). But yeah, I'll run the release once we're in agreement over whether this should be 1.0.0 or just another artifact for 0.12.0-M2.

**Comment by larsrh** [comment]
I have no opinion on this. Feel free to go along how you prefer.

**Pull request merged**
