### PR TITLE
master -> main

### PR DESCRIPTION
**Pull request by rossabaker**
I pushed a main branch.  If this is approved, instead of merging, we can just change the default and delete the master branch.

### CODE REVIEW

**Comment by larsrh** [comment]
Fair enough with me. So we can close this?

**Comment by travisbrown** [comment]
We'll still need the badge link to change. Also for projects with open PRs I think we don't want to delete `master` at first, since that will close PRs that target it, but just to change the default.

**Comment by larsrh** [comment]
@rossabaker has already made that change on `main`. I think we can just switch the default branch to `main`, delete `master`, and call it a day.

**Comment by travisbrown** [comment]
@larsrh Ah, got it, thanks.

**Pull request closed without merging**
