### PR TITLE
Drop discipline-scalatest and discipline-specs2

### PR DESCRIPTION
**Pull request by rossabaker**
We'd like to release a discipline-1.0.0 for cats to depend on.  If we released that now, we'd be releasing discipline-scalatest-1.0.0 on a prerelease, which is not ideal.  We need to:

1) Decouple their release cycles by moving them to separate repos.
2) Discontinue discipline-scalatest and discipline-specs2, which aren't big anyway.

Either way, this is a step toward unblocking cats-2.0.0-RC1.

### CODE REVIEW

**Comment by larsrh** [comment]
Who wants to run the release?

**Comment by rossabaker** [comment]
I'll try right now.

**Comment by rossabaker** [comment]
Done, but I am following up with an update to the README.

**Comment by rossabaker** [comment]
I spoke too soon.  `sbt release` didn't sign the artifacts or release the repo.  Trying again the hard way.

**Comment by rossabaker** [comment]
Okay, _now_ I got it.

**Pull request merged**
