### PR TITLE
update to Scala 2.13.0-M4

### LINKED ISSUE #52: Switch to ScalaCheck 1.14.0
There are some nice new features in 1.14.0 (for example, displaying/setting test seed), but it is binary incompatible with the previous version. This means that Discipline using 1.13.5 prevents us from using the current versions of both ScalaCheck and Specs2.

### LINKED ISSUE #53: Publish for 2.13.0-M4

### PR DESCRIPTION
**Pull request by larsrh**
Fixes #52
Fixes #53

### CODE REVIEW

**Comment by larsrh** [comment]
Okay. That didn't work. I ran `++ 2.13.0-M4` locally instead of `++ 2.13.0-M4!`. :man_facepalming:

**Comment by larsrh** [comment]
@djspiewak Missing releases:

* [ ] specs2
* [ ] scalatest

**Comment by djspiewak** [comment]
Ping @etorreborre and @bvenners.

**Comment by etorreborre** [comment]
Note that I am currently trying to re-deploy, after updating all the code, but something is hopelessly slow and grinds to a halt. I will try from home tonight.

**Comment by djspiewak** [comment]
@etorreborre Sounds like sonatype! ;-)

**Comment by etorreborre** [comment]
Yes I don't know what's wrong with Sonatype but the publish task has been running for hours now and is still not finished :-(.

**Comment by xuwei-k** [comment]
- https://repo1.maven.org/maven2/org/specs2/specs2-core_2.13.0-M4/
- https://repo1.maven.org/maven2/org/scalatest/scalatest_2.13.0-M4/

**Comment by larsrh** [comment]
I pushed an updated commit but it turns out that introduces a binary compatibility problem for Scala 2.10. Do we still need it?

**Comment by etorreborre** [comment]
@larsrh I dropped 2.10 some time ago now. With 2.13 around the corner I think it is reasonable.

**Comment by larsrh** [comment]
I've asked in [cats-dev](https://gitter.im/typelevel/cats-dev?at=5b2df1ab6ceffe4eba2a6e96).

**Comment by larsrh** [comment]
Fixes #52
Fixes #53

**Pull request merged**
