### PR TITLE
Bump ScalaCheck to 1.13.0

### PR DESCRIPTION
**Pull request by adelbertc**
Probably pending a non-SNAPSHOT release for https://github.com/scalatest/scalatest/issues/837

### CODE REVIEW

**Comment by larsrh** [comment]
There appears to be some version clash with Scala.js. Unfortunately I have no idea what to do about that :frowning:

**Comment by non** [comment]
Yeah I have ran into this too. I wonder if @bvenners has seen it?

**Comment by adelbertc** [comment]
Could it be related to not having a published JS SNAPSHOT for that milestone? https://github.com/scalatest/scalatest/issues/837#issuecomment-200531772

**Comment by adelbertc** [comment]
OK I lied, he does have JS SNAPSHOT published: https://github.com/scalatest/scalatest/issues/837#issuecomment-200548791

On a related note, are we OK with depending on a SNAP (a stable SNAPSHOT) release, or would we like to wait for a more final release?

On a more selfish note, this decision impacts how quickly we can fix the Cats build.

**Comment by adelbertc** [comment]
Seems it was just an incompatible version of Scala.JS. Fixed now.

**Comment by larsrh** [comment]
Thanks, merged!

**Comment by adelbertc** [comment]
Sweet - what's the roadmap looking like for the next release?

**Comment by larsrh** [comment]
I could either wait for #18 or cut one now, what would you prefer?

**Comment by adelbertc** [comment]
@larsrh [Let's wait](https://github.com/non/algebra/pull/144), I'll try to ping/PR again when ScalaTest makes a non-SNAP release

**Pull request merged**
