### PR TITLE
Migrate to sbt-typelevel

### PR DESCRIPTION
**Pull request by armanbilge**

### CODE REVIEW

**Comment by armanbilge** [comment]
It seems that binary compatibility was broken on Scala 3, and I can't understand how/why.
```
[error] discipline: Failed binary compatibility check against org.typelevel:discipline-core_3:1.3.0 (e:info.versionScheme=early-semver)! Found 1 potential problems
[error]  * static method const(Boolean)org.typelevel.discipline.Predicate in interface org.typelevel.discipline.Predicate does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("org.typelevel.discipline.Predicate.const")
```

**Comment by armanbilge** [comment]
Oh, was 1.3.0 on Scala 3.1?

**Comment by vasilmkd** [comment]
We're only as good as the tools given to us. @rossabaker, can you please set up the publishing credentials for this repo too? Thank you.

**Comment by rossabaker** [comment]
@armanbilge, I increased your access so you can set it.

**Comment by armanbilge** [comment]
@vasilmkd secrets are installed, merge at will.

**Review by vasilmkd — APPROVED** [review]

**Pull request merged**
