### PR TITLE
bump Dotty to stable

### PR DESCRIPTION
**Pull request by larsrh**

### CODE REVIEW

**Comment by travisbrown** [comment]
:+1:, thanks. Out of curiosity, is there a reason not to go straight to the 0.24.0 RC?

**Comment by larsrh** [comment]
I want to release for a stable version.

**Comment by travisbrown** [comment]
Ah, okay. I think it would be good to aim for a consistent policy across projects in this respect, which means there are a couple of open questions:

* Do we publish Dotty artifacts for projects where there's no particular benefit over using the 2.13 artifacts on Dotty? If a project or its dependencies rely on macros (like ScalaTest), that's a reason to publish for Dotty, or if it could benefit from the new derivation mechanism (like circe-core). For things like Jawn or this project, neither of those are the case, and it seems like we're committing to a lot of unnecessary maintenance work if we start publish Dotty releases now instead of just "officially" recommending the 2.13 artifacts via `withDottyCompat`.
* For libraries that we do publish for Dotty, do we target RCs or only stable releases? The general trend seems to be to target RCs (e.g. that's what MUnit, ScalaTest, and Circe do).

**Comment by larsrh** [comment]
Good point. Not sure what to do there. I'll think about it.

**Comment by larsrh** [comment]
I have reached out to Darja to hear the Scala Center's thought. So far, it seems like they don't see a big benefit in _releasing_ Dotty artifacts (this doesn't apply to CI builds, naturally, which has a big benefit for future migration).

**Comment by travisbrown** [comment]
@larsrh Agreed, that sounds reasonable.

**Pull request merged**
