### PR TITLE
Split out test-library-specific modules, drop optional deps

### PR DESCRIPTION
**Pull request by travisbrown**
The ScalaTest dependency here is proving to be extremely annoying, since pretty much everything in the Typelevel ecosystem depends on Discipline. Ideally discipline-scalatest would be separately versioned, but this is a start.

### CODE REVIEW

**Comment by travisbrown** [comment]
This is a breaking change, of course, so it'd be really cool if we could get it (or something equivalent) into the laws modules in Cats 2.0.

**Comment by travisbrown** [comment]
As an example of the kind of problem this (partially) solves: the following example is broken with the latest versions of Discipline and ScalaTest:

```scala
import org.scalatest.funsuite.AnyFunSuite
import org.typelevel.discipline.scalatest.Discipline

object MyTest extends AnyFunSuite with Discipline
```

It's true that these are all milestones or `-SNAP` versions, but even once we've got a stable ScalaTest 3.1.0 there will be reasons to worry about this (ScalaTest doesn't have a great bincompat track record, 3.2 has been around the corner for years, etc.).

**Comment by travisbrown** [comment]
And for a concrete example of how this dependency is causing real problems right now: [we want to publish an Algebra 2.0.0 release](https://gitter.im/typelevel/general?at=5ce147b4ef853135c8e86322), but algebra-laws depends on Discipline, so if we make this Algebra release 2.0.0, anyone using the eventual ScalaTest 3.1.0 release and a transitive Discipline dependency will see the breakage above.

**Comment by travisbrown** [comment]
My thinking is that discipline-scalatest (and discipline-specs2) would carry some kind of use-at-your-own-risk warning that would track the latest stable ScalaTest with no bincompat guarantees, with the idea being that anyone who needs support for a different ScalaTest from the one currently supported can just define their own `checkAll` in a few lines of code.

I don't think we need to decide how to settle that issue now, though—the goal of this PR is to let us get a stable Discipline 0.12.0 (or 1.0.0?) out the door without these dependencies, and we can work out the module versioning later.

**Comment by larsrh** [comment]
I probably merged this in the wrong order, sorry. This one has conflicts now.

**Comment by travisbrown** [comment]
@larsrh No worries, I expected one would end up needing resolution!

**Pull request merged**
