### PR TITLE
Scala 2.13.0-RC2

### PR DESCRIPTION
**Pull request by jhnsmth**
Currently blocked by  scalatest/scalatestplus-scalacheck#6

### CODE REVIEW

**Comment by larsrh** [comment]
Very strange that Travis didn't build this PR :thinking:

**Comment by jhnsmth** [comment]
It's because I added `[ci skip]` to the last commit, as it's broken anyway because of missing scalatestplus-scalacheck for RC2, so not to waste ci resources

**Comment by travisbrown** [comment]
@jhnsmth This should work with 1.0.0-SNAP5 now.

**Comment by larsrh** [comment]
Closed in favour of #98.

**Pull request closed without merging**
