### PR TITLE
update to scalatest 3.1.0-SNAP9

### PR DESCRIPTION
**Pull request by kailuowang**
can we release a milestone with this so that Cats can release a milestone with 3.1.0-SNAP as well?

### CODE REVIEW

**Comment by larsrh** [comment]
#88 is identical and failed. Probably needs some additional code changes, too.

**Comment by kailuowang** [comment]
I'll work on it. shall we close the robot one?

**Comment by kailuowang** [comment]
closed for now, will reopen once I get it working locally.

**Comment by larsrh** [comment]
Yes, please continue here.

**Comment by kailuowang** [comment]
@larsrh build passed.

**Comment by SethTisue** [comment]
the Scala community build is still on ScalaTest 3.0.x, so I'll just freeze discipline at cc79369

**Comment by larsrh** [comment]
0.11.2-M1 is on its way to Maven Central

**Pull request merged**
